name: Test Traceable AST Init Action And Traceable AST Run Action
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  AstScan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Init scan action
        uses: traceable-github-actions/traceable-ast
        with:
          step_name: 'init'
          client_scan_token: '89duuMVedPJO-TXXW9L77gOpW8hfaIBqgtY147XLWlCt6'
          traffic_env: 'crapi-demo-1'
          traceable_server: ${{ secrets.TRACEABLE_SERVER }}
      - name: Run a loop as functional test (This is sample)
        run: |
          for ((i=1;i<=100;i++));
          do
             echo $i
          done
      - name: Run scan action
        uses: traceable-github-actions/traceable-ast
        with:
          step_name: 'run'
          client_scan_token: '89duuMVedPJO-TXXW9L77gOpW8hfaIBqgtY147XLWlCt6'
          traffic_env: 'crapi-demo-1'
          cli_version: '1.0.0-rc.3'
